app/rutas/ciudad/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify,session,abort
from app.Models.CiudadModel import CiudadModel
from app.helps.helps import limpiar_campo

# Se modularizan las vistas de ciudades.
mod = Blueprint("ciudad", __name__, template_folder="templates")

@mod.before_request
def before_request():
    if 'username' not in session:
        return redirect(url_for('login.login'))
    elif 'grupo' not in session:
        return redirect(url_for('login.login'))
    elif 'username' in session and 'grupo' in session and session['grupo'] not in ('ADMIN'):
        abort(403, description="Acceso prohibido")

@mod.route("/")
def index_ciudad():
    cm = CiudadModel()
    items = cm.listarTodos()        
    return render_template('ciudad/index.html', items = items)

@mod.route("/frm_ciudad")
def frm_ciudad():
    return render_template('ciudad/frm_ciudad.html')

@mod.route("/guardar", methods = ["POST"])
def guardar_ciudad():
    
    # Comprobar si el metodo utilizado es POST.
    if request.method == "POST":
        
        # Recolectar datos del formulario.
        idciudad =  request.form["idciudad"]
        descripcion = request.form["txtdescripcion"]
        descripcion = limpiar_campo(descripcion)
        
        # Comprobar si el campo idciudad esta cargado.
        if len(idciudad) > 0:
            
            # Modificar
            if descripcion != "" and descripcion != None and len(descripcion) != 0:
                cm = CiudadModel()
                resul = cm.modificar(idciudad, descripcion)
                if resul == True:
                    flash("Exito, se salvo correctamente", "success")
                    return redirect(url_for('ciudad.index_ciudad'))
                else:
                    flash(resul, "danger")
                    return redirect(url_for('ciudad.index_ciudad'))                            
            else:
                flash("Error, el campo no puede estar vacio", "danger")
                return redirect(url_for('ciudad.index_ciudad'))


        else:

            # Guardar
            if descripcion != "" and descripcion != None and len(descripcion) != 0:
                cm = CiudadModel()
                resul = cm.guardar(descripcion)
                if resul == True:
                    flash("Exito, se salvo correctamente", "success")
                    return redirect(url_for('ciudad.index_ciudad'))
                else:
                    flash(resul, "danger")
                    return redirect(url_for('ciudad.index_ciudad'))                            
            else:
                flash("Error, el campo no puede estar vacio", "danger")
                return redirect(url_for('ciudad.index_ciudad'))

    else:
        return "Error en la peticion"

@mod.route('/modificar/<int:idciudad>')
def modificar_ciudad(idciudad):

    cm = CiudadModel()
    datos = cm.recuperaCiudad(idciudad)

    return render_template('ciudad/frm_ciudad.html', datos = datos)

@mod.route('eliminar/<idciudad>')
def eliminar_ciudad(idciudad):

    cm = CiudadModel()
    res = cm.eliminar(idciudad)
    
    if res == True:
        flash("Se elimino correctamente", "success")
        return redirect(url_for('ciudad.index_ciudad'))
    else:
        flash(res, "warning")
        return redirect(url_for('ciudad.index_ciudad'))

@mod.route('/listar_ciudades')
def listar_ciudades():
    cm = CiudadModel()
    items = cm.listarTodos()
    print(items)    
    return jsonify({"data":items})

app/rutas/ciudad/templates/ciudad/frm_ciudad.html
{% extends 'base.html' %}
{% from 'render_elements.html' import pintar_input,pintar_button  %}

{% block title %}
Inicio
{% endblock %}

{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                                <a href="{{ url_for('ciudad.index_ciudad') }}"
                                class="btn btn-secondary bt-sm">
                                <i class="fa fa-angle-left"></i> Volver
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Mantener Ciudad</h3>
                            </div>
                            <hr>
                            <form action="{{ url_for('ciudad.guardar_ciudad') }}" method="post" >
                                <input type="hidden" name="idciudad" value="{{ datos[0] if datos else '' }}">
                                {{ pintar_input("Descripción", "txtdescripcion", "Aregua...", "text",  datos[1] if datos else "" ) }}
                                <div class="row">
                                    <div class="col-lg-6">
                                        {{ pintar_button("Guardar", "btnguardar", "",type="submit") }}
                                    </div>
                                    <div class="col-lg-6">
                                        {{ pintar_button("Cancelar", "btncancelar", "",type="reset") }}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MAIN CONTENT-->
<!-- END PAGE CONTAINER-->
{% endblock %}

app/rutas/ciudad/templates/ciudad/index.html
{% extends 'base.html' %}
{% from 'render_elements.html' import pintar_alerta %}


{% block title %}
Mantener Ciudades
{% endblock %}

{% block mi_css%}
<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-confirm.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.bootstrap4.min.css') }}">
{% endblock %}

{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title-3 m-b-30">Mantener Ciudades</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-12 mb-2">
                                    <a href="{{ url_for('ciudad.frm_ciudad') }}"
                                        class="au-btn au-btn-icon au-btn--green au-btn--small">
                                        <i class="zmdi zmdi-plus"></i>Agregar
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive table--no-card m-b-30">
                                <table id="tabla_ciudad" class="table table-borderless table-striped table-earning">
                                    <thead>
                                        <tr>
                                            <th>Descripción</th>
                                            <th class="text-right">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        {% for item in items %}
                                        <tr>
                                            <td>{{ item[1] }}</td>
                                            <td>
                                                <div class="table-data-feature">

                                                    <button onclick="modificar({{ item[0] }})" class="item btn btn-warning modificar"
                                                        data-toggle="tooltip" data-placement="top" title="Modificar">
                                                        <i class="zmdi zmdi-edit"></i>
                                                    </button>
                                                    <button onclick="eliminar({{ item[0] }})" class="item btn btn-danger"
                                                        data-toggle="tooltip" data-placement="top" title="Eliminar">
                                                        <i class="zmdi zmdi-delete"></i>
                                                    </button>

                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor%}

                                    </tbody>
                                </table>
                                {{ pintar_alerta(messages) }}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MAIN CONTENT-->
<!-- END PAGE CONTAINER-->
{% endblock %}

{% block mi_script %}
<script src="{{ url_for('static', filename='js/jquery-confirm.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ url_for('static', filename='js/dataTables.buttons.js') }}"></script>
<script src="{{ url_for('static', filename='js/buttons.bootstrap4.js') }}"></script>
<script src="{{ url_for('static', filename='js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ url_for('static', filename='jsOperacionales/ciudad.js') }}"></script>
{% endblock %}